// <auto-generated />
namespace HPMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class restockalert : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(restockalert));
        
        string IMigrationMetadata.Id
        {
            get { return "201808032225567_restockalert"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
